# Generated by Django 5.2.1 on 2025-11-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_search_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midiresult',
            old_name='name',
            new_name='midi_name',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='result',
            new_name='dictMidi',
        ),
        migrations.RemoveField(
            model_name='midiresult',
            name='created_at',
        ),
    ]
