# Generated by Django 5.2.1 on 2025-11-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_rename_name_midiresult_midi_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midiresult',
            name='file_midi',
        ),
    ]
