# Generated by Django 5.2.1 on 2025-11-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_midiresult_file_midi'),
    ]

    operations = [
        migrations.AddField(
            model_name='midiresult',
            name='file_midi',
            field=models.FilePathField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='midiresult',
            name='file_notes_pdf',
            field=models.FilePathField(default=False),
            preserve_default=False,
        ),
    ]
