# Generated by Django 5.2.1 on 2025-11-17 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_midiresult_file_midi_midiresult_file_notes_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midiresult',
            name='file_notes_pdf',
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transposition', models.SmallIntegerField()),
                ('midi_track', models.SmallIntegerField()),
                ('file_pdf', models.FilePathField()),
                ('file_png', models.FilePathField()),
                ('midi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midi', to='notes.midiresult')),
            ],
        ),
    ]
