# Generated by Django 5.2.1 on 2026-03-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_remove_midiresult_file_notes_pdf_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MidiResult',
            new_name='Midi',
        ),
        migrations.RenameModel(
            old_name='Notes',
            new_name='SheetMusic',
        ),
    ]
